name: Check Format

on:
  pull_request:
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: "20.x"
          check-latest: true

      - name: Install Packages
        run: npm install

      - name: Run prettier
        run: npx prettier . --write

      - name: Check Format
        id: format
        run: git diff --exit-code
