name: Code Format
 
on: 
  push:
    branches: 
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: '20.x'
          check-latest: true

      - name: Install remark
        run: npm install remark-cli remark-preset-lint-consistent remark-preset-lint-recommended remark-toc --save-dev --global
 
      - name: Run remark
        run: remark docs -o
 
      - name: Check Format
        id: format
        run: git diff --exit-code
      
      - name: Create Pull Request
        if: steps.format.conclusion == 'failure'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: '[Bot] format'
          title: '[Bot] Auto format'
          branch: bot/format
          delete-branch: true
          labels: |
            bot
            format
          draft: false
          body: |
            This PR is created by a bot to format in the repository.